# You can read the original repo maintainers.toml at:
# https://forge.fedoraproject.org/releng/kiwi-descriptions/src/branch/rawhide/maintainers.toml

# Surface Pro 12" customizations
[surface-pro-12-inch]
fas = [ "SayaAndy" ]
maintainers = [ "Saya Andy" ]
